version: '2'
networks:
  mired2: #Nombre de la red
    ipam: #Administra las direcciones ips
      config: #Etiqueta usada para definir la configuración de la red
       - subnet: 182.28.0.0/16 #Aquí definimos la subred a usar
         gateway: 182.28.0.1 #Aquí definimos la puerta de enlace de la red
services: #Esta etiqueta es usada para definir los contenedores que instalaremos en Docker
  db: #Nombre del servicio
    image: bitnami/mongodb:latest
    container_name: mongo_db #Nombre del contenedor en nuestro Docker
    networks:
      mired2:
        ipv4_address: 182.28.0.11 #Dirección ip del contenedor
    ports:
      - "27017:27017" #Especificamos los puertos
    expose:
      - 27017 #Expone los puertos sin publicarlos al host.

  app-persons:
    image: rubenespada/microservicio_agenda:v2
    container_name: personsapp
    networks:
      mired2:
        ipv4_address: 182.28.0.12
    expose:
    - 80
    ports:
    - "80:8080"
    depends_on: #En esta etiqueta colocamos de qué servicio depende este contenedor
    - db
